#! /usr/bin/env bash

USAGE="How to use ./run
===

  $ ./run \\
    [COMMAND]                  # Optionally provide a command to run

If no COMMAND is provided, \`run\` will be run.

Commands
---

- build: Build image
- run: Run the container
- test: Run tests
- ruff: Check code style
- clean: Remove image
"

# Read optional arguments
while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
    key="$1"

    case $key in
        -h|--help) echo "$USAGE"; exit ;;
    esac
    shift
done

# Find current run command
run_command=${1:-}
if [[ -n "${run_command}" ]]; then shift; fi


case $run_command in
    ""|"run")
    echo "Building newscorp:dev"

    docker build . -t "newscorp:dev"

    docker run --volume "$(pwd)"/data:/app/data --rm newscorp:dev poetry run main
    ;;
    "build")
    echo "Building newscorp:dev"
    docker build . -t "newscorp:dev"
    ;;
    "tests")
    docker run --rm newscorp:dev poetry run tests
    ;;
    "ruff")
    docker run --rm newscorp:dev poetry run ruff check scripts.py tests/* newscorp/*
    ;;
    "clean")
    docker rmi newscorp:dev
    ;;
esac